# Export Terraform variable values to an Ansible var_file
#File Location ansible/group_vars/all
resource "local_file" "tf_ansible_vars_file_new" {
  content  = <<-DOC
    ---
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    project_db_endpoint: ${var.project_db_endpoint}
    project_cache_endpoint: ${var.project_cache_endpoint}
    elasticsearch_private_ip: ${var.elasticsearch_private_ip}
    admin_private_ip: ${var.admin_private_ip}
    elasticsearch_public_ip: ${var.elasticsearch_public_ip}
    admin_public_ip: ${var.admin_public_ip}
    project_elasticsearch_name: ${var.project_name}-elasticsearch
    project_nfs_name: ${var.project_name}-nfs
    nfs_private_ip: ${var.nfs_private_ip}
    nfs_public_ip: ${var.nfs_public_ip}
    project_domain_name: ${var.project_name}.${var.project_domain}
    project_domain_pma: ${var.project_domain_pma}
    project_admin_name: ${var.project_name}
    user_project_firstname: ${var.user_project_firstname}
    user_project_lastname: ${var.user_project_lastname}
    user_project_email: ${var.user_project_email}
    project_plan: ${var.project_plan}

    DOC
  filename = "./../ansible/group_vars/all/tf_ansible_vars_file.yml"
}