---
ansible_user: admin
ansible_become: yes 

db_user_pass: "{{ lookup('ansible.builtin.env', 'db_user_pass') }}"
pma_project_pass: "{{ lookup('ansible.builtin.env', 'pma_project_pass') }}"

magento_public_key: "{{ lookup('ansible.builtin.env', 'magento_public_key') }}"
magento_private_key: "{{ lookup('ansible.builtin.env', 'magento_private_key') }}"
aws_rds_master_pass: "{{ lookup('ansible.builtin.env', 'aws_rds_master_pass') }}"

#Some extra var
#mag_admin_password: "{{ lookup('password', '/dev/null length=22 chars=ascii_letters,digits') }}"